In [1]:
import pandas as pd

In [92]:
li=pd.read_excel('https://docs.google.com/spreadsheets/d/e/2PACX-1vR9N95aRIL4ckYana9gRKC7uLf2kaQA3E1XAy0aPxhNRB0D5PsX1gMgvvFgElgLt_DsCY8GrPoq6pSD/pub?output=xlsx')

In [93]:
li['num']=li['NOMBRE COMPLETO'].str.split().apply(len)

In [238]:
n='Rodolfo Jose Maria Salas Lopez'
def getlongnames(n,nn={}):
    import re
    ilast=100 #just a large integer
    pos=[]
    i=0
    if len(n.split())<=4:
        print('WARNING: Expected long name with at most of 4 words')
    for p in n.split():
        i=i+1
        if re.search('\w',p, re.UNICODE):
            if len(p)<=3:
                ilast=i
                pos.append(i)
    if len(pos)>1 and (pd.np.array(pos[1:])-pd.np.array(pos[:-1])).max()>1:
        #special cases
        ilast=pos[0]
    if ilast<3:
        nn['NOMBRES']  =(' ').join( n.split()[:3] )
        nn['APELLIDOS']=(' ').join( n.split()[3:])
    elif ilast<4 and len(pos)>1:
        nn['NOMBRES']  =(' ').join( n.split()[:4] )
        nn['APELLIDOS']=(' ').join( n.split()[4:])
    else:
        nn['NOMBRES']  =(' ').join( n.split()[:2] )
        nn['APELLIDOS']=(' ').join( n.split()[2:])
    
    return nn

In [239]:
getlongnames(n)

{'APELLIDOS': 'Maria Salas Lopez', 'NOMBRES': 'Rodolfo Jose'}

In [240]:
def getnames(n):
    nn={}
    if len(n.split())==4:
        nn['NOMBRES']  =(' ').join( n.split()[:2] )
        nn['APELLIDOS']=(' ').join( n.split()[-2:] )
    elif len(n.split())==3:
        nn['NOMBRES']  =(' ').join( n.split()[:2] )
        nn['APELLIDOS']=(' ').join( n.split()[-1:] )
    elif len(n.split())==2:
        nn['NOMBRES']  =(' ').join( n.split()[:1] )
        nn['APELLIDOS']=(' ').join( n.split()[-1:] )
    elif len(n.split())>4:
        nn=getlongnames(n,nn)
    else:
        nn=None
    return nn

In [241]:
li['NOMBRES Y APELLIDOS']=li['NOMBRE COMPLETO'].apply( getnames )
#li['APELLIDOS']=li['NOMBRE COMPLETO'].apply( getlastnames )

In [242]:
li[li.num>4].loc[7].values

array(['Favio David Guerra - Acero PARRA', 6,
       {'NOMBRES': 'Favio David', 'APELLIDOS': 'Guerra - Acero PARRA'}],
      dtype=object)

In [243]:
li[li.num>4]

,NOMBRE COMPLETO,num,NOMBRES Y APELLIDOS
7,Favio David Guerra - Acero PARRA,6,"{'NOMBRES': 'Favio David', 'APELLIDOS': 'Guerr..."
37,Magnolia del Pilar Ballesteros Cabrera,5,"{'NOMBRES': 'Magnolia del Pilar', 'APELLIDOS':..."
80,Soraya de la Asuncion Colina Matiz,6,"{'NOMBRES': 'Soraya de la Asuncion', 'APELLIDO..."
123,María Consuelo Del Pilar Amaya Rey,6,"{'NOMBRES': 'María Consuelo Del Pilar', 'APELL..."
164,María del Pilar Soler Parra,5,"{'NOMBRES': 'María del Pilar', 'APELLIDOS': 'S..."
246,Analida del Socorro Estrada Bedoya,5,"{'NOMBRES': 'Analida del Socorro', 'APELLIDOS'..."
292,Rodrigo De Jesus Aponte Penso,5,"{'NOMBRES': 'Rodrigo De Jesus', 'APELLIDOS': '..."
296,MANUEL DE JESUS BELTRAN ESPITIA,5,"{'NOMBRES': 'MANUEL DE JESUS', 'APELLIDOS': 'B..."
308,Maria de los Angeles Maytorena Noriega,6,"{'NOMBRES': 'Maria de los Angeles', 'APELLIDOS..."
366,SONIA DEL CARMEN BELALCAZAR BELALCAZAR,5,"{'NOMBRES': 'SONIA DEL CARMEN', 'APELLIDOS': '..."
452,Lucy Maria Alejandra Leal Granados,5,"{'NOMBRES': 'Lucy Maria', 'APELLIDOS': 'Alejan..."
474,Karla del Pilar Trujillo Calderón,5,"{'NOMBRES': 'Karla del Pilar', 'APELLIDOS': 'T..."
475,Hans Walter Acero De La Parra,6,"{'NOMBRES': 'Hans Walter', 'APELLIDOS': 'Acero..."
506,Emma Adriana De la Rosa Alzate,6,"{'NOMBRES': 'Emma Adriana', 'APELLIDOS': 'De l..."
515,MARÍA DE JESÚS QUINTERO MONROY,5,"{'NOMBRES': 'MARÍA DE JESÚS', 'APELLIDOS': 'QU..."
530,Ana María del Río González,5,"{'NOMBRES': 'Ana María del', 'APELLIDOS': 'Río..."
542,Juan Manuel Martin Uribe Cano,5,"{'NOMBRES': 'Juan Manuel', 'APELLIDOS': 'Marti..."
580,Dora Isabel GARZON DE LAVERDE,5,"{'NOMBRES': 'Dora Isabel', 'APELLIDOS': 'GARZO..."
598,Isabel Cristina Suarez Del Chiaro,5,"{'NOMBRES': 'Isabel Cristina', 'APELLIDOS': 'S..."
606,Blanca Ruby Rendon De Arboleda,5,"{'NOMBRES': 'Blanca Ruby', 'APELLIDOS': 'Rendo..."
613,Adriana Liceth Alvarez De la Hoz,6,"{'NOMBRES': 'Adriana Liceth', 'APELLIDOS': 'Al..."
663,Monica del Carmen Espeleta Maradei,5,"{'NOMBRES': 'Monica del Carmen', 'APELLIDOS': ..."
684,Maria Del Carmen Pichardo Martinez,5,"{'NOMBRES': 'Maria Del Carmen', 'APELLIDOS': '..."
698,Helmer De Jesus Zapata Ossa,5,"{'NOMBRES': 'Helmer De Jesus', 'APELLIDOS': 'Z..."
704,María del Socorro Pelaez Lozano,5,"{'NOMBRES': 'María del Socorro', 'APELLIDOS': ..."
726,Cirit Del Carmen Mateus De Oro,6,"{'NOMBRES': 'Cirit Del Carmen', 'APELLIDOS': '..."
736,Elisama Esther Beltran De La Rosa,6,"{'NOMBRES': 'Elisama Esther', 'APELLIDOS': 'Be..."
738,KAREN VIVIANA LASCANO GONZALEZ RUBIO,5,"{'NOMBRES': 'KAREN VIVIANA', 'APELLIDOS': 'LAS..."
740,Osmar De Jesus PEREZ PEREZ,5,"{'NOMBRES': 'Osmar De Jesus', 'APELLIDOS': 'PE..."
746,Esneider de Jesus Mora Lopéz,5,"{'NOMBRES': 'Esneider de Jesus', 'APELLIDOS': ..."
...,...,...,...
3814,MARTHA RAQUEL SOFÍA NIÑO CHACÓN,5,"{'NOMBRES': 'MARTHA RAQUEL', 'APELLIDOS': 'SOF..."
3902,Edwin Yair Oliveros - Ariz,5,"{'NOMBRES': 'Edwin Yair', 'APELLIDOS': 'Oliver..."
3974,Monica Del Rosario PEREZ URIBE,5,"{'NOMBRES': 'Monica Del Rosario', 'APELLIDOS':..."
4003,Rodolfo Jose Maria Salas Lopez,5,"{'NOMBRES': 'Rodolfo Jose', 'APELLIDOS': 'Mari..."
4063,Ximena Sanz de Santama Cárdenas,5,"{'NOMBRES': 'Ximena Sanz', 'APELLIDOS': 'de Sa..."
4103,JOSÉ DE JESÚS MORENO CORREA,5,"{'NOMBRES': 'JOSÉ DE JESÚS', 'APELLIDOS': 'MOR..."
4109,Maria Del Carmen JIMENEZ RUIZ,5,"{'NOMBRES': 'Maria Del Carmen', 'APELLIDOS': '..."
4196,Fabio De Jesús Jurado Valencia,5,"{'NOMBRES': 'Fabio De Jesús', 'APELLIDOS': 'Ju..."
4247,Silvia María Antonia Rivera Largacha,5,"{'NOMBRES': 'Silvia María', 'APELLIDOS': 'Anto..."
4301,juanita del pilar bejarano celis,5,"{'NOMBRES': 'juanita del pilar', 'APELLIDOS': ..."
4343,Henry Leonardo Rivera Rivera Garcia,5,"{'NOMBRES': 'Henry Leonardo', 'APELLIDOS': 'Ri..."
4411,María Del Socorro Guzmán Serna,5,"{'NOMBRES': 'María Del Socorro', 'APELLIDOS': ..."
4413,Mariana De Los Angeles Villarraga Velásquez,6,"{'NOMBRES': 'Mariana De Los Angeles', 'APELLID..."
4427,Juan David Roa De La Torre,6,"{'NOMBRES': 'Juan David', 'APELLIDOS': 'Roa De..."
4430,Grey Del Carmen Jiménez Gómez,5,"{'NOMBRES': 'Grey Del Carmen', 'APELLIDOS': 'J..."
4443,Synella Del Sol Montaño Niebles,5,"{'NOMBRES': 'Synella Del Sol Montaño', 'APELLI..."
4447,Greys De Jesus Jimenez Barrios,5,"{'NOMBRES': 'Greys De Jesus', 'APELLIDOS': 'Ji..."
4461,Diana Lucia Del Castillo Cadavid,5,"{'NOMBRES': 'Diana Lucia', 'APELLIDOS': 'Del C..."
4640,Julio Antonio Olivera La Rosa,5,"{'NOMBRES': 'Julio Antonio', 'APELLIDOS': 'Oli..."
4667,Jorge Nilsón Harvey Barco Pérez,5,"{'NOMBRES': 'Jorge Nilsón', 'APELLIDOS': 'Harv..."
4720,Raúl Alberto Avendaño De León,5,"{'NOMBRES': 'Raúl Alberto', 'APELLIDOS': 'Aven..."
4745,MARIA DEL PILAR VEGA PIDIACHE,5,"{'NOMBRES': 'MARIA DEL PILAR', 'APELLIDOS': 'V..."
4805,YESSICA PAHOLA TORREZ DE LA ROSA,6,"{'NOMBRES': 'YESSICA PAHOLA', 'APELLIDOS': 'TO..."
4814,Mery del Carmen Jessica Lois C Montenegro Cas...,8,"{'NOMBRES': 'Mery del Carmen', 'APELLIDOS': 'J..."
4817,Alvaro De Jesus Alvarez Rivera,5,"{'NOMBRES': 'Alvaro De Jesus', 'APELLIDOS': 'A..."
4820,Carmen Ysabel Martínez de Meriño,5,"{'NOMBRES': 'Carmen Ysabel', 'APELLIDOS': 'Mar..."
4875,JOSE DEL CARMEN VILLALOBOS TOVAR,5,"{'NOMBRES': 'JOSE DEL CARMEN', 'APELLIDOS': 'V..."
4899,Laura Jocelyn De Castro Laurens,5,"{'NOMBRES': 'Laura Jocelyn', 'APELLIDOS': 'De ..."
4927,Lissy Yalile Alvarez delPino Ricard,5,"{'NOMBRES': 'Lissy Yalile', 'APELLIDOS': 'Alva..."
4929,MANUEL DE JESUS BELTRAN ESPITIA,5,"{'NOMBRES': 'MANUEL DE JESUS', 'APELLIDOS': 'B..."